-- Import Lua modules
require('plugins')
require('core/options')
require('core/autocmds')
require('core/keymaps')
require('core/colors')
require('core/statusline')
require('config/lspconfig')
require('config/mason')
require('config/nvim-cmp')
require('config/nvim-tree')
require('config/nvim-treesitter')
require('config/telescope')
require('config/indent-blankline')

vim.cmd('language en_US.utf8')
