-- Setup orgmode
-- require('orgmode').setup({
--   -- org_agenda_files = { '~/org/inbox/*.org', '~/org/mode.d/tasks/**/*.org' },
--   org_agenda_files = { '~/org/inbox/*' },
--   org_default_notes_file = '~/org/mode.d/notes/notes.org',
--   -- org_todo_keywords = {'TODO', 'WAITING', '|', 'DONE', 'DELEGATED'},
--   -- treesitter = { enable = false },
--   org_todo_keyword_faces = {
--       WAITING = ':foreground blue :weight bold',
--       DELEGATED = ':background #FFFFFF :slant italic :underline on',
--       TODO = ':background #000000 :foreground red', -- overrides builtin color for `TODO` keyword
--   },
-- })
--
-- -- -- Treesitter configuration to disable Org parser
-- require('nvim-treesitter.configs').setup({
--   ensure_installed = "all",  -- or list your installed languages here
--   ignore_install = { "org" },  -- prevent installing the Org parser
-- })

-- require("org-roam").setup({
--   directory = "~/org/roam.d",
--   -- optional
--   -- Org_files = {
--   --   "~/another_org_dir",
--   --   "~/some/folder/*.org",
--   --   "~/a/single/org_file.org",
--   -- }
-- })
